### ISSUE TITLE
Migrate React.PropTypes to prop-types

### ISSUE THREAD

**Issue by jp7carlos** [gakimball/react-inky#10]
Hi,

I created a pull request that fixes many warnings that it's currently emitting: https://github.com/gakimball/react-inky/pull/9

Some of these fixes included adding ```<tbody>``` between ```<table>``` and  ```<tr>```, which might not be the exact same result that Inky generates. 

So take a look at it when you have time.

Thx!

**Comment by gakimball** [comment]
In the future, could you submit different changes as separate pull requests? That makes them easier to individually merge and review. Thanks :)

I'll leave a review in the pull request.

**Comment by jp7carlos** [comment]
I apologize. I did not know the commits made after creating the pull request would be added to it.
