### ISSUE TITLE
Version 0.3.0

### ISSUE THREAD

**Issue by gakimball** [gakimball/react-inky#13]
Ideas for another iteration of this thing.

## Revised `<Spacer />`

With React 16.2's `<Fragment />`, we can now recreate spacers the exact way they work in Inky.

## Custom Wrapper HTML

Something like this. It gives you the flexibility to modify the `<head>` of the email.

```jsx
import Inky from 'inky';
import Newsletter from './templates/newsletter';

const email = (
  <Inky>
    <Inky.Head>
      <title>Newsletter for 04/14/18</title>
      <link rel="stylesheet" href="/static/style.css" />
    </Inky.Head>
    <Inky.Body>
      <Inky.Preview text="Text below subject line" />
      <Newsletter />
    </Inky.Body>
  </Inky>
);
```

One slightly annoying thing is that you can't add a doctype in JSX, so it would have to be added manually. There could maybe be a `doctype` constant exported from the package that includes the correct XHTML doctype.

**Comment by gakimball** [comment]
Now available under the `next` tag:

```
npm install react-inky@next
```

**Comment by alarner** [comment]
This tripped me up a bit but if you're using `react-inky@next` there is actually not an Inky.Preview component. Instead use the param on the body, eg: `<Inky.Body preview="...">`

**Comment by gakimball** [comment]
Ah yeah, sorry about that! I ended up doing it a little differently than this issue.

**Comment by mir3z** [comment]
@gakimball When are you planning to release v0.3?

**Comment by gakimball** [comment]
@mir3z I don't think I'm going to add anything else to it, so I could release it soon. In the mean time, you can try it out with `npm install gakimball/react-inky#0.3`. If you have any feedback, let me know!

**Comment by gakimball** [comment]
@mir3z It's out now!
