### ISSUE TITLE
Missing tbody?

### ISSUE THREAD

**Issue by mir3z** [gakimball/react-inky#17]
I've noticed some of the components have missing `tbody` under `table` which makes html invalid. If you try to render using `ReactDOM.render` React even complains about that.

According to:
* https://github.com/zurb/inky/blob/develop/lib/makeColumn.js
* https://github.com/zurb/inky/blob/develop/lib/componentFactory.js

Every `table` has `tbody`.

**Comment by gakimball** [comment]
You're looking at the `develop` branch of inky, which has unpublished commits. react-inky imitates the latest version of inky, so whenever that's released, this library can be updated to match 👌
