### ISSUE TITLE
Failed to build with webpack

### ISSUE THREAD

**Issue by Cherviakov** [gakimball/react-inky#19]
nodejs: 11.1.0
webpack: 3.12.0
react-inky 0.4.0

ERROR in ./node_modules/react-attrs-filter/build/index.js
Module not found: Error: Can't resolve '../data/' in '..myProject/node_modules/react-attrs-filter/build'

**Comment by gakimball** [comment]
Are you trying to build the library itself, or did you install it into another project?

**Comment by Cherviakov** [comment]
@gakimball we tring to use react-inky in our project

**Comment by gakimball** [comment]
Could you post your Webpack config, and the code where you're importing react-inky?

**Comment by awinograd** [comment]
The same issue is happening to me. If I change the require in `react-attrs-filter` from `../data/` to `../data/index.json` it works

**Comment by ghost** [comment]
Not working on that project anymore, do there no additional context. Closing.
