### ISSUE TITLE
When I use .map to show a series of images, how can I style it?

### ISSUE THREAD

**Issue by yinshengabc** [gakimball/react-inky#28]
In react, I use this function to send a series of images in an email:
{images.map(image => {
            return (
              ...)
How can I fix to a specific number of the columns in a row? Or can do the same style as {display:flex and flex-wrap} in CSS.
Thanks a lot.

**Comment by gakimball** [comment]
Do you have a specific layout in mind, like for example having three images per row no matter what?

**Comment by yinshengabc** [comment]
> Do you have a specific layout in mind, like for example having three images per row no matter what?

Sure, something like that. I want four images per row, however the total number of images is not fixed. For example: I have 15 images, it would be 3*4+3 ; if I have 16 images, it would be 4*4.

**Comment by gakimball** [comment]
Got it. So with this grid, columns don't wrap like they would in a normal grid system. So you need to split the array into smaller arrays of equal size, and render one row for each chunk. Something like this (sample code—didn't run it in anything):

```jsx
import React from 'react'
import { Row, Column } from 'react-inky'
import chunk from 'lodash/chunk'

const Images = ({ images }) => {
  return (
    <>
      {chunk(images, 3).map((chunk, (chunkIndex)) => (
        <Row key={chunkIndex}>
          {chunk.map((image, imageIndex) => (
            <Column key={imageIndex} large="4" />
          ))}
        </Row>
      ))}
    </>
  )
}
```

**Comment by yinshengabc** [comment]
> Got it. So with this grid, columns don't wrap like they would in a normal grid system. So you need to split the array into smaller arrays of equal size, and render one row for each chunk. Something like this (sample code—didn't run it in anything):
> 
> ```js-jsx
> import React from 'react'
> import { Row, Column } from 'react-inky'
> import chunk from 'lodash/chunk'
> 
> const Images = ({ images }) => {
>   return (
>     <>
>       {chunk(images, 3).map((chunk, (chunkIndex)) => (
>         <Row key={chunkIndex}>
>           {chunk.map((image, imageIndex) => (
>             <Column key={imageIndex} large="4" />
>           ))}
>         </Row>
>       ))}
>     </>
>   )
> }
> ```
I see. Thank you very much, I appreciate.
